Repository Meettify/backend, pull requests merged in 2024-10, with the labels that each got.

#134 [Feat] 모임 권한 정보 가져오는 기능 구현
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/dto/meet/MeetRole.java
Labels: Feat

#230 [Feat] Category enum 클래스 구현
  build.gradle
  src/main/java/com/example/meettify/dto/meet/category/Category.java
Labels: Feat

#248 [Fix] 모임 상세 기능 이미지 로직 에러 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/dto/meet/MeetDetailDTO.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Fix

#249 [Fix] 모임 게시판 이미지 등록 로직 에러 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardControllerDocs.java
  src/main/java/com/example/meettify/dto/meetBoard/MeetBoardServiceDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardDTO.java
Labels: Fix

#251 [Modify] 모임 리스트 기능 검색기능으로 변경
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
  src/main/java/com/example/meettify/dto/meet/MeetSearchCondition.java
  src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
  src/main/java/com/example/meettify/repository/meet/CustomMeetRepository.java
  src/main/java/com/example/meettify/repository/meet/MeetRepository.java
  src/main/java/com/example/meettify/repository/meet/MeetRepositoryImpl.java
  src/main/java/com/example/meettify/service/meet/MeetService.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#253 [Modify] 모임 삭제로직 모임 이미지 S3에서 삭제 되도록 수정
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#255 [Modify] 모임 변경 기능 모임 이미지 S3에서 삭제 되도록 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
  src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
  src/main/java/com/example/meettify/dto/meet/UpdateMeetDTO.java
  src/main/java/com/example/meettify/service/meet/MeetService.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#257 [Modify] 모임 게시판 삭제 기능 이미지 S3에서 삭제 되도록 수정
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Modify

#259 [Modify] 모임 게시판 변경시 모임 이미지 S3에서 삭제 되도록 수정
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardControllerDocs.java
  src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardServiceDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/UpdateRequestMeetBoardDTO.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Modify

#260 [Feat] 가입 모임 리스트 보여주기 구현
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
  src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
  src/main/java/com/example/meettify/service/meet/MeetService.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Feat

#262 [Modify] 가입 모임 리스트에 권한 정보 추가
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#264 [Feat] 모임 탈퇴하기 기능 구현
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meet/MeetControllerDocs.java
  src/main/java/com/example/meettify/dto/meet/MeetRole.java
  src/main/java/com/example/meettify/dto/meet/MyMeetResponseDTO.java
Labels: Feat

#272 [Feat] 공지사항 기능 구현
  grafana/grafana.db
  src/main/java/com/example/meettify/config/security/SecurityConfig.java
  src/main/java/com/example/meettify/controller/notice/NoticeController.java
  src/main/java/com/example/meettify/controller/notice/NoticeControllerDocs.java
  src/main/java/com/example/meettify/dto/board/ResponseBoardDTO.java
  src/main/java/com/example/meettify/entity/notice/NoticeEntity.java
  src/main/java/com/example/meettify/repository/notice/NoticeRepository.java
  src/main/java/com/example/meettify/service/notice/NoticeService.java
  src/main/java/com/example/meettify/service/notice/NoticeServiceImpl.java
Labels: Feat

#277 [Feat] 공지사항 페이징 기능 구현
  grafana/grafana.db
  src/main/java/com/example/meettify/controller/notice/NoticeController.java
  src/main/java/com/example/meettify/controller/notice/NoticeControllerDocs.java
  src/main/java/com/example/meettify/repository/notice/NoticeRepository.java
  src/main/java/com/example/meettify/service/notice/NoticeService.java
  src/main/java/com/example/meettify/service/notice/NoticeServiceImpl.java
Labels: Feat

#279 [Feat] accessToken 재발급 기능 구현
  grafana/grafana.db
  src/main/java/com/example/meettify/config/jwt/JwtProvider.java
  src/main/java/com/example/meettify/controller/jwt/TokenController.java
  src/main/java/com/example/meettify/controller/jwt/TokenControllerDocs.java
  src/main/java/com/example/meettify/entity/jwt/TokenEntity.java
  src/main/java/com/example/meettify/service/jwt/TokenService.java
  src/main/java/com/example/meettify/service/jwt/TokenServiceImpl.java
Labels: Feat

#280 [Feat] 전체 검색기능 구현
  src/main/java/com/example/meettify/controller/search/SearchController.java
  src/main/java/com/example/meettify/controller/search/SearchControllerDocs.java
  src/main/java/com/example/meettify/dto/meet/MeetSummaryDTO.java
  src/main/java/com/example/meettify/dto/search/SearchCondition.java
  src/main/java/com/example/meettify/dto/search/SearchEntityDTO.java
  src/main/java/com/example/meettify/dto/search/SearchResponseDTO.java
  src/main/java/com/example/meettify/repository/search/SearchCustomRepositoryImpl.java
  src/main/java/com/example/meettify/service/search/SearchService.java
  src/main/java/com/example/meettify/service/search/SearchServiceImpl.java
Labels: Feat

#282 [Fix] 모임 게시글 댓글 @Builder 경고
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardCommentEntity.java
Labels: Fix

#284 [Fix] QCommunityEntity 필드 오류 수정
  src/main/java/com/example/meettify/repository/search/SearchCustomRepositoryImpl.java
Labels: Fix

#285 [Modify] 모임 게시판 댓글 API Swagger문서 수정
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentControllerDocs.java
Labels: Modify

#286 [Fix] 모임 디테일 에러 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Fix

#289 [Modify] 모임 수정 API 명세서 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/dto/meet/UpdateMeetDTO.java
  src/main/java/com/example/meettify/dto/meet/UpdateMeetServiceDTO.java
Labels: Modify

#292 [Modify] 모임관련 Security 접근 권한 수정
  src/main/java/com/example/meettify/config/security/SecurityConfig.java
  src/main/java/com/example/meettify/controller/meet/MeetController.java
Labels: Modify

#296 [Modify] 검색관련 Security 접근 권한 수정
  src/main/java/com/example/meettify/config/security/SecurityConfig.java
  src/main/java/com/example/meettify/controller/search/SearchController.java
Labels: Modify

#297 [Fix] 상품 전체 조회 해결하기
  grafana/grafana.db
  src/main/java/com/example/meettify/dto/item/ItemSearchCondition.java
  src/main/java/com/example/meettify/repository/item/ItemRepositoryImpl.java
Labels: Fix

#310 [Remove] SearchEntityDTO 삭제
  src/main/java/com/example/meettify/dto/search/SearchEntityDTO.java
  src/main/java/com/example/meettify/repository/search/SearchCustomRepositoryImpl.java
  src/main/java/com/example/meettify/service/search/SearchServiceImpl.java
Labels: Remove

#311 [Fix] 모임 변경 에러 수정
  src/main/java/com/example/meettify/entity/meet/MeetEntity.java
Labels: Fix

#312 [Modify] 모임 인원 수에 맞게 인원 받도록 수정
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#315 [Fix] 모임 멤버 오류 수정
  src/main/java/com/example/meettify/controller/community/CommunityController.java
  src/main/java/com/example/meettify/dto/board/ResponseCommunityDTO.java
  src/main/java/com/example/meettify/dto/meet/ResponseMeetMemberDTO.java
  src/main/java/com/example/meettify/dto/search/SearchResponseDTO.java
  src/main/java/com/example/meettify/service/community/CommunityService.java
  src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
  src/main/java/com/example/meettify/service/notice/NoticeServiceImpl.java
  src/main/java/com/example/meettify/service/search/SearchServiceImpl.java
Labels: Fix

#326 [Fix] 레디스 RedisTemplate 빈문제 해결
  grafana/grafana.db
  src/main/java/com/example/meettify/config/redis/RedisConfig.java
  src/main/resources/application-prod.yml
Labels: Fix

#330 [Feat] 모임 게시판 대댓글 수정 기능 구현
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardCommentController.java
  src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardCommentDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardCommentDTO.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentService.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardCommentServiceImpl.java
Labels: Feat

#348 [Fix] 모임 리스트 에러 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
Labels: Fix

#350 [Fix] redis 조회수 증가 에러 고치기
  src/main/java/com/example/meettify/config/redis/RedisConfig.java
  src/main/java/com/example/meettify/config/redis/RedisService.java
  src/main/java/com/example/meettify/controller/community/CommunityController.java
  src/main/java/com/example/meettify/dto/board/ResponseCommunityDTO.java
  src/main/java/com/example/meettify/repository/community/CommunityRepository.java
  src/main/java/com/example/meettify/service/community/CommunityService.java
  src/main/java/com/example/meettify/service/community/CommunityServiceImpl.java
Labels: Fix

#380 [Modify] 모임 리스트 페이지 기본값 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
Labels: Modify
