Repository Meettify/backend, pull requests merged in 2024-09, with the labels that each got.

#22 [Comment] gradle 설명 주석 추가
  build.gradle
Labels: Comment

#23 [Feat] JWT 기능 구현
  build.gradle
  src/main/generated/com/example/meettify/entity/jwt/QTokenEntity.java
  src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/meettify/config/jwt/JwtProvider.java
  src/main/java/com/example/meettify/config/jwt/JwtSecurityConfig.java
  src/main/java/com/example/meettify/dto/jwt/TokenDTO.java
  src/main/java/com/example/meettify/entity/jwt/TokenEntity.java
Labels: Feat

#25 [Feat] exception 기능 구현
  src/main/java/com/example/meettify/exception/GlobalExceptionAdvice.java
  src/main/java/com/example/meettify/exception/board/BoardException.java
  src/main/java/com/example/meettify/exception/cart/CartException.java
  src/main/java/com/example/meettify/exception/comment/CommentException.java
  src/main/java/com/example/meettify/exception/externalService/ExternalServiceException.java
  src/main/java/com/example/meettify/exception/file/FileDownloadException.java
  src/main/java/com/example/meettify/exception/file/FileUploadException.java
  src/main/java/com/example/meettify/exception/item/ItemException.java
  src/main/java/com/example/meettify/exception/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/meettify/exception/jwt/JwtAccessHandler.java
  src/main/java/com/example/meettify/exception/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/meettify/exception/member/MemberException.java
  src/main/java/com/example/meettify/exception/order/OrderException.java
  src/main/java/com/example/meettify/exception/sessionExpire/SessionExpiredException.java
  src/main/java/com/example/meettify/exception/stock/OutOfStockException.java
  src/main/java/com/example/meettify/exception/validation/DataValidationException.java
Labels: Feat

#26 [Feat] signUp 기능 구현
  src/main/generated/com/example/meettify/entity/jwt/QTokenEntity.java
  src/main/java/com/example/meettify/config/auditing/AuditingConfig.java
  src/main/java/com/example/meettify/config/auditing/AuditorConfigImpl.java
  src/main/java/com/example/meettify/config/auditing/entity/BaseEntity.java
  src/main/java/com/example/meettify/config/auditing/entity/BaseTimeEntity.java
  src/main/java/com/example/meettify/config/modelMapper/RootConfig.java
  src/main/java/com/example/meettify/config/security/SecurityConfig.java
  src/main/java/com/example/meettify/controller/member/MemberController.java
  src/main/java/com/example/meettify/dto/member/AddressDTO.java
  src/main/java/com/example/meettify/dto/member/MemberServiceDTO.java
  src/main/java/com/example/meettify/dto/member/RequestMemberDTO.java
  src/main/java/com/example/meettify/dto/member/ResponseMemberDTO.java
  src/main/java/com/example/meettify/dto/member/role/UserRole.java
  src/main/java/com/example/meettify/entity/member/AddressEntity.java
  src/main/java/com/example/meettify/entity/member/MemberEntity.java
  src/main/java/com/example/meettify/repository/member/MemberRepository.java
  src/main/java/com/example/meettify/service/member/MemberService.java
  src/main/java/com/example/meettify/service/member/MemberServiceImpl.java
Labels: Feat

#27 [Comment] 예외처리 주석 추가
  src/main/java/com/example/meettify/exception/GlobalExceptionAdvice.java
  src/main/java/com/example/meettify/exception/board/BoardException.java
  src/main/java/com/example/meettify/exception/cart/CartException.java
  src/main/java/com/example/meettify/exception/comment/CommentException.java
  src/main/java/com/example/meettify/exception/externalService/ExternalServiceException.java
  src/main/java/com/example/meettify/exception/file/FileDownloadException.java
  src/main/java/com/example/meettify/exception/file/FileUploadException.java
  src/main/java/com/example/meettify/exception/item/ItemException.java
  src/main/java/com/example/meettify/exception/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/meettify/exception/jwt/JwtAccessHandler.java
  src/main/java/com/example/meettify/exception/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/meettify/exception/member/MemberException.java
  src/main/java/com/example/meettify/exception/order/OrderException.java
  src/main/java/com/example/meettify/exception/sessionExpire/SessionExpiredException.java
  src/main/java/com/example/meettify/exception/stock/OutOfStockException.java
  src/main/java/com/example/meettify/exception/validation/DataValidationException.java
Labels: Comment

#28 [Feat] login 기능 구현
  src/main/java/com/example/meettify/controller/member/MemberController.java
  src/main/java/com/example/meettify/dto/member/LoginDTO.java
  src/main/java/com/example/meettify/repository/jwt/TokenRepository.java
  src/main/java/com/example/meettify/service/member/MemberService.java
  src/main/java/com/example/meettify/service/member/MemberServiceImpl.java
Labels: Add

#29 [Add] git action & docker
  .github/workflows/action.yml
  build.gradle
  docker/Dockerfile
  docker/docker-compose.yml
Labels: Add

#31 [Feat] 회원탈퇴 기능 구현
  src/main/java/com/example/meettify/controller/member/MemberController.java
  src/main/java/com/example/meettify/service/member/MemberService.java
  src/main/java/com/example/meettify/service/member/MemberServiceImpl.java
Labels: Feat

#35 [Add] 설정 파일 추가
  .github/workflows/action.yml
  .gitignore
  build.gradle
  docker-compose.yml
  docker/Dockerfile
  docker/api/Dockerfile
  docker/docker-compose.yml
  prometheus.yml
  scripts/load-test.js
Labels: Add

#36 [Modify] action.yml 수정
  .github/workflows/action.yml
Labels: Modify

#47 [Feat] 모임 엔티티 구성하기
  src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
  src/main/java/com/example/meettify/dto/meet/RequestMeetDTO.java
  src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
  src/main/java/com/example/meettify/dto/meet/category/Category.java
  src/main/java/com/example/meettify/entity/Category.java
  src/main/java/com/example/meettify/entity/Meet/MeetBoardEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetBoardImageEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetImageEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetMemberEntity.java
Labels: Feat

#49 [Fix] 모임 권한 관련 클래스 추가
  src/main/java/com/example/meettify/controller/member/MemberController.java
  src/main/java/com/example/meettify/entity/Meet/MeetBoardEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetBoardImageEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetImageEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetMemberEntity.java
  src/main/java/com/example/meettify/entity/Meet/MeetRole.java
  src/main/java/com/example/meettify/repository/meet/MeetImageRepository.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
Labels: Fix

#50 [Feat] OAuth2.0 로그인 기능 구현
  .github/workflows/action.yml
  .gitignore
  src/main/java/com/example/meettify/config/oauth/GoogleUser.java
  src/main/java/com/example/meettify/config/oauth/NaverUser.java
  src/main/java/com/example/meettify/config/oauth/OAuth2FailHandler.java
  src/main/java/com/example/meettify/config/oauth/OAuth2SuccessHandler.java
  src/main/java/com/example/meettify/config/oauth/OAuthProviderUser.java
  src/main/java/com/example/meettify/config/oauth/OAuthUserInfo.java
  src/main/java/com/example/meettify/config/oauth/PrincipalOAuthUserService.java
  src/main/java/com/example/meettify/config/security/PrincipalDetails.java
  src/main/java/com/example/meettify/config/security/PrincipalDetailsService.java
  src/main/java/com/example/meettify/config/security/SecurityConfig.java
  src/main/java/com/example/meettify/dto/member/SocialDTO.java
  src/main/java/com/example/meettify/entity/member/MemberEntity.java
Labels: Feat

#51 [Fix] 생성자 에러를 고침
  src/main/java/com/example/meettify/config/oauth/OAuthProviderUser.java
Labels: Fix

#57 [Feat] S3 이미지 올리기 기능 구현
  .github/workflows/action.yml
  build.gradle
  docker-compose.yml
  docker/api/Dockerfile
  src/main/java/com/example/meettify/MeettifyApplication.java
  src/main/java/com/example/meettify/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/meettify/config/s3/FileDTOFactory.java
  src/main/java/com/example/meettify/config/s3/S3Config.java
  src/main/java/com/example/meettify/config/s3/S3ImageUploadService.java
Labels: Feat

#62 [Fix] 모임 게시판 MeetBoardRepository JPQL 파라미터 매핑 오류 해결하기
  src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java
Labels: Fix

#64 [Feat] Git Action main 파이프라인 기능 구현
  .github/workflows/action.yml
Labels: Feat

#66 [Chore] 모임 엔티티 디렉토리 구조 변경, 클래스명 수정
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/dto/meet/UpdateMeetServiceDTO.java
  src/main/java/com/example/meettify/entity/meet/MeetEntity.java
  src/main/java/com/example/meettify/entity/meet/MeetImageEntity.java
  src/main/java/com/example/meettify/entity/meet/MeetMemberEntity.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardImageEntity.java
  src/main/java/com/example/meettify/repository/meet/MeetImageRepository.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
  src/main/java/com/example/meettify/repository/meet/MeetRepository.java
  src/main/java/com/example/meettify/repository/meetBoard/MeetBoardImageRepository.java
  src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java
  src/main/java/com/example/meettify/service/meet/MeetService.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Chore

#67 [Modify] Jib 기능으로 수정
  .github/workflows/action.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/example/meettify/entity/meet/MeetMemberEntity.java
Labels: Modify

#70 [Feat] 모임 게시판 요약 정보 제공 기능 구현
  src/main/java/com/example/meettify/dto/meetBoard/MeetBoardSummaryDTO.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Feat

#73 [Modify] 배열로 받는 부분 List로 수정
  src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
  src/main/java/com/example/meettify/dto/meet/RequestMeetDTO.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
Labels: Modify

#95 [Feat] 모임 게시글 작성 기능
  src/main/java/com/example/meettify/controller/meet/MeetController.java
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/dto/meet/MeetServiceDTO.java
  src/main/java/com/example/meettify/dto/meet/ResponseMeetDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/MeetBoardServiceDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/RequestMeetBoardDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/ResponseMeetBoardDetailsDTO.java
  src/main/java/com/example/meettify/entity/meet/MeetImageEntity.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardImageEntity.java
  src/main/java/com/example/meettify/service/meet/MeetServiceImpl.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Feat

#96 [Feat] 모임 게시글 삭제하기
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/entity/meet/MeetEntity.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
  src/main/java/com/example/meettify/repository/meet/MeetMemberRepository.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Feat

#97 [Feat] 모임 게시글 수정하기
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/dto/meetBoard/UpdateMeetBoardServiceDTO.java
  src/main/java/com/example/meettify/dto/meetBoard/UpdateRequestMeetBoardDTO.java
  src/main/java/com/example/meettify/entity/meetBoard/MeetBoardEntity.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Feat

#103 [Feat] 모임 게시글 페이징 기능 구현
  src/main/java/com/example/meettify/controller/meetBoard/MeetBoardController.java
  src/main/java/com/example/meettify/dto/meetBoard/MeetBoardSummaryDTO.java
  src/main/java/com/example/meettify/repository/meetBoard/MeetBoardRepository.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardService.java
  src/main/java/com/example/meettify/service/meetBoard/MeetBoardServiceImpl.java
Labels: Feat
